import { Product } from '../states/product/Product.context';

const productListMock = (): Product[] => {
    console.warn('You are using Mock ProductList');
    return [
        {
            id: '1',
            name: 'Laptop X1',
            price: 1299.99,
            size: '15.6 inches',
            category: 'Electronics',
            brand: 'TechPro',
            description: 'Powerful laptop for work and play.',
            image: 'laptop_x1.jpg',
            stock: 50,
            rating: 4.5,
            reviews: 120,
        },
        {
            id: '2',
            name: 'Smartphone Z5',
            price: 799.0,
            size: '6.1 inches',
            category: 'Electronics',
            brand: 'MobileMax',
            description: 'High-end smartphone with advanced camera.',
            image: 'smartphone_z5.jpg',
            stock: 75,
            rating: 4.2,
            reviews: 85,
        },
        {
            id: '3',
            name: 'Gaming Headset G10',
            price: 99.5,
            size: 'One Size',
            category: 'Electronics',
            brand: 'AudioAce',
            description: 'Immersive gaming headset with surround sound.',
            image: 'headset_g10.jpg',
            stock: 100,
            rating: 4.8,
            reviews: 200,
        },
        {
            id: '4',
            name: 'Office Chair C2',
            price: 199.99,
            size: 'Adjustable',
            category: 'Furniture',
            brand: 'ComfortKing',
            description: 'Ergonomic office chair with lumbar support.',
            image: 'chair_c2.jpg',
            stock: 30,
            rating: 4.0,
            reviews: 40,
        },
        {
            id: '5',
            name: 'Standing Desk D1',
            price: 399.5,
            size: '60 x 30 inches',
            category: 'Furniture',
            brand: 'DeskMaster',
            description: 'Adjustable standing desk for improved posture.',
            image: 'desk_d1.jpg',
            stock: 25,
            rating: 4.6,
            reviews: 60,
        },
        {
            id: '6',
            name: 'Running Shoes R3',
            price: 89.99,
            size: "Men's 10",
            category: 'Sports & Outdoors',
            brand: 'SpeedStride',
            description: 'Lightweight running shoes for optimal performance.',
            image: 'shoes_r3.jpg',
            stock: 80,
            rating: 4.3,
            reviews: 95,
        },
        {
            id: '7',
            name: 'Yoga Mat Y2',
            price: 29.5,
            size: 'Standard',
            category: 'Sports & Outdoors',
            brand: 'ZenYoga',
            description: 'Non-slip yoga mat for comfortable practice.',
            image: 'mat_y2.jpg',
            stock: 120,
            rating: 4.7,
            reviews: 150,
        },
        {
            id: '8',
            name: 'Backpack B1',
            price: 49.99,
            size: '20L',
            category: 'Travel',
            brand: 'TravelGear',
            description: 'Durable backpack for travel and everyday use.',
            image: 'backpack_b1.jpg',
            stock: 60,
            rating: 4.1,
            reviews: 55,
        },
        {
            id: '9',
            name: 'Travel Pillow P2',
            price: 19.5,
            size: 'Neck Pillow',
            category: 'Travel',
            brand: 'RestEasy',
            description: 'Memory foam travel pillow for comfortable travel.',
            image: 'pillow_p2.jpg',
            stock: 150,
            rating: 4.9,
            reviews: 250,
        },
        {
            id: '10',
            name: 'Wireless Headphones H5',
            price: 149.99,
            size: 'Over-Ear',
            category: 'Electronics',
            brand: 'SoundWave',
            description: 'Noise-cancelling wireless headphones.',
            image: 'headphones_h5.jpg',
            stock: 40,
            rating: 4.4,
            reviews: 110,
        },
        {
            id: '11',
            name: 'Coffee Maker M1',
            price: 79.5,
            size: '12 cups',
            category: 'Kitchen & Dining',
            brand: 'BrewBuddy',
            description: 'Programmable coffee maker with automatic shut-off.',
            image: 'coffeemaker_m1.jpg',
            stock: 90,
            rating: 4.3,
            reviews: 70,
        },
        {
            id: '12',
            name: 'Blender B2',
            price: 59.99,
            size: '50 oz',
            category: 'Kitchen & Dining',
            brand: 'BlendIt',
            description: 'Powerful blender for smoothies and soups.',
            image: 'blender_b2.jpg',
            stock: 110,
            rating: 4.6,
            reviews: 130,
        },
        {
            id: '13',
            name: 'Cookware Set S1',
            price: 129.99,
            size: '10 piece',
            category: 'Kitchen & Dining',
            brand: "Chef'sChoice",
            description: 'Non-stick cookware set for easy cooking.',
            image: 'cookware_s1.jpg',
            stock: 35,
            rating: 4.2,
            reviews: 65,
        },
        {
            id: '14',
            name: 'Bookcase B3',
            price: 149.5,
            size: '5 shelves',
            category: 'Furniture',
            brand: 'Bookworm',
            description:
                'Stylish bookcase for storing books and displaying décor.',
            image: 'bookcase_b3.jpg',
            stock: 20,
            rating: 4.7,
            reviews: 80,
        },
        {
            id: '15',
            name: 'Table Lamp T1',
            price: 39.99,
            size: '18 inches',
            category: 'Home Décor',
            brand: 'LightStyle',
            description: 'Modern table lamp with adjustable brightness.',
            image: 'lamp_t1.jpg',
            stock: 70,
            rating: 4.5,
            reviews: 100,
        },
        {
            id: '16',
            name: 'Area Rug A1',
            price: 99.99,
            size: '5 x 7 feet',
            category: 'Home Décor',
            brand: 'Rugged',
            description:
                'Soft and plush area rug for adding warmth to any room.',
            image: 'rug_a1.jpg',
            stock: 55,
            rating: 4.4,
            reviews: 90,
        },
        {
            id: '17',
            name: 'Throw Blanket T2',
            price: 29.5,
            size: '50 x 60 inches',
            category: 'Home Décor',
            brand: 'CozyComfort',
            description:
                'Soft and cozy throw blanket for snuggling up on the couch.',
            image: 'blanket_t2.jpg',
            stock: 100,
            rating: 4.8,
            reviews: 180,
        },
        {
            id: '18',
            name: 'Canvas Print C1',
            price: 49.5,
            size: '24 x 36 inches',
            category: 'Home Décor',
            brand: 'Artful',
            description:
                'Beautiful canvas print for adding a touch of art to your home.',
            image: 'canvas_c1.jpg',
            stock: 45,
            rating: 4.6,
            reviews: 75,
        },
        {
            id: '19',
            name: 'Garden Tools Set G1',
            price: 39.99,
            size: '5 piece',
            category: 'Patio, Lawn & Garden',
            brand: 'GreenThumb',
            description: 'Essential garden tools for planting and weeding.',
            image: 'gardentools_g1.jpg',
            stock: 85,
            rating: 4.3,
            reviews: 120,
        },
        {
            id: '20',
            name: 'Outdoor Furniture Set F1',
            price: 299.99,
            size: '4 piece',
            category: 'Patio, Lawn & Garden',
            brand: 'OutdoorOasis',
            description:
                'Durable and stylish outdoor furniture set for your patio or deck.',
            image: 'furniture_f1.jpg',
            stock: 25,
            rating: 4.5,
            reviews: 50,
        },
        {
            id: '21',
            name: 'Grill G2',
            price: 199.5,
            size: 'Propane',
            category: 'Patio, Lawn & Garden',
            brand: 'GrillMaster',
            description: 'High-performance propane grill for outdoor cooking.',
            image: 'grill_g2.jpg',
            stock: 30,
            rating: 4.7,
            reviews: 100,
        },
        {
            id: '22',
            name: 'Camping Tent T3',
            price: 149.99,
            size: '4 person',
            category: 'Sports & Outdoors',
            brand: 'AdventureGear',
            description: 'Waterproof camping tent for outdoor adventures.',
            image: 'tent_t3.jpg',
            stock: 65,
            rating: 4.4,
            reviews: 85,
        },
        {
            id: '23',
            name: 'Sleeping Bag S2',
            price: 79.5,
            size: 'Adult',
            category: 'Sports & Outdoors',
            brand: 'SleepSound',
            description: 'Warm and comfortable sleeping bag for camping.',
            image: 'sleepingbag_s2.jpg',
            stock: 95,
            rating: 4.6,
            reviews: 140,
        },
        {
            id: '24',
            name: 'Hiking Boots H1',
            price: 129.5,
            size: "Men's 11",
            category: 'Sports & Outdoors',
            brand: 'Trailblazer',
            description: 'Durable hiking boots for rugged terrain.',
            image: 'boots_h1.jpg',
            stock: 50,
            rating: 4.3,
            reviews: 75,
        },
        {
            id: '25',
            name: 'Desk Organizer O1',
            price: 19.99,
            size: 'Multi-compartment',
            category: 'Office Supplies',
            brand: 'OrganizeIt',
            description: 'Desk organizer for keeping your workspace tidy.',
            image: 'organizer_o1.jpg',
            stock: 120,
            rating: 4.7,
            reviews: 160,
        },
        {
            id: '26',
            name: 'Notebook N1',
            price: 9.99,
            size: 'College ruled',
            category: 'Office Supplies',
            brand: 'NoteTaker',
            description:
                'Spiral notebook for taking notes and jotting down ideas.',
            image: 'notebook_n1.jpg',
            stock: 200,
            rating: 4.8,
            reviews: 220,
        },
        {
            id: '27',
            name: 'Pen Set P3',
            price: 14.5,
            size: '12 pack',
            category: 'Office Supplies',
            brand: 'WriteRite',
            description: 'Set of ballpoint pens for smooth writing.',
            image: 'pens_p3.jpg',
            stock: 150,
            rating: 4.6,
            reviews: 110,
        },
        {
            id: '28',
            name: 'Stapler S3',
            price: 12.99,
            size: 'Heavy duty',
            category: 'Office Supplies',
            brand: 'StapleIt',
            description: 'Heavy-duty stapler for securing documents.',
            image: 'stapler_s3.jpg',
            stock: 75,
            rating: 4.4,
            reviews: 60,
        },
        {
            id: '29',
            name: 'Printer Paper P4',
            price: 24.99,
            size: '500 sheets',
            category: 'Office Supplies',
            brand: 'PrintPerfect',
            description:
                'High-quality printer paper for crisp and clear prints.',
            image: 'paper_p4.jpg',
            stock: 100,
            rating: 4.9,
            reviews: 190,
        },
        {
            id: '30',
            name: 'Dog Food D2',
            price: 39.99,
            size: '25 lbs',
            category: 'Pet Supplies',
            brand: 'DoggyDelights',
            description: 'Nutritious dog food for adult dogs.',
            image: 'dogfood_d2.jpg',
            stock: 60,
            rating: 4.5,
            reviews: 130,
        },
        {
            id: '31',
            name: 'Cat Food C3',
            price: 29.5,
            size: '15 lbs',
            category: 'Pet Supplies',
            brand: 'KittyKibble',
            description: 'Premium cat food for all life stages.',
            image: 'catfood_c3.jpg',
            stock: 80,
            rating: 4.7,
            reviews: 170,
        },
        {
            id: '32',
            name: 'Pet Bed B4',
            price: 49.99,
            size: 'Large',
            category: 'Pet Supplies',
            brand: 'PetRest',
            description: 'Comfortable pet bed for dogs and cats.',
            image: 'petbed_b4.jpg',
            stock: 40,
            rating: 4.3,
            reviews: 90,
        },
        {
            id: '33',
            name: 'Pet Toys T4',
            price: 19.99,
            size: 'Variety pack',
            category: 'Pet Supplies',
            brand: 'PlayfulPets',
            description: 'Variety pack of pet toys for dogs and cats.',
            image: 'pettoys_t4.jpg',
            stock: 100,
            rating: 4.6,
            reviews: 150,
        },
        {
            id: '34',
            name: 'Pet Carrier C4',
            price: 39.5,
            size: 'Airline approved',
            category: 'Pet Supplies',
            brand: 'TravelPets',
            description:
                'Airline-approved pet carrier for safe and comfortable travel.',
            image: 'petcarrier_c4.jpg',
            stock: 55,
            rating: 4.4,
            reviews: 80,
        },
        {
            id: '35',
            name: 'Board Game B5',
            price: 29.99,
            size: '2-4 players',
            category: 'Toys & Games',
            brand: 'GameNight',
            description: 'Fun and engaging board game for family and friends.',
            image: 'boardgame_b5.jpg',
            stock: 75,
            rating: 4.8,
            reviews: 160,
        },
        {
            id: '36',
            name: 'Puzzle P5',
            price: 19.5,
            size: '1000 pieces',
            category: 'Toys & Games',
            brand: 'PuzzlePro',
            description: 'Challenging puzzle for adults and older children.',
            image: 'puzzle_p5.jpg',
            stock: 120,
            rating: 4.6,
            reviews: 110,
        },
        {
            id: '37',
            name: 'Building Blocks B6',
            price: 49.99,
            size: '500 pieces',
            category: 'Toys & Games',
            brand: 'BlockBuilders',
            description: 'Creative building blocks for children of all ages.',
            image: 'buildingblocks_b6.jpg',
            stock: 90,
            rating: 4.7,
            reviews: 140,
        },
        {
            id: '38',
            name: 'Stuffed Animal A2',
            price: 14.99,
            size: '12 inches',
            category: 'Toys & Games',
            brand: 'SoftStuffed',
            description: 'Soft and cuddly stuffed animal for children.',
            image: 'stuffedanimal_a2.jpg',
            stock: 150,
            rating: 4.9,
            reviews: 200,
        },
        {
            id: '39',
            name: 'Remote Control Car C5',
            price: 39.5,
            size: 'Off-road',
            category: 'Toys & Games',
            brand: 'RemoteRacers',
            description: 'Off-road remote control car for exciting races.',
            image: 'car_c5.jpg',
            stock: 60,
            rating: 4.4,
            reviews: 95,
        },
        {
            id: '40',
            name: 'Digital Camera C6',
            price: 499.99,
            size: '20.1 MP',
            category: 'Electronics',
            brand: 'PhotoPro',
            description:
                'High-resolution digital camera for capturing stunning photos.',
            image: 'camera_c6.jpg',
            stock: 45,
            rating: 4.6,
            reviews: 125,
        },
        {
            id: '41',
            name: 'Tablet T5',
            price: 299.5,
            size: '10.1 inches',
            category: 'Electronics',
            brand: 'TabletTech',
            description: 'Versatile tablet for entertainment and productivity.',
            image: 'tablet_t5.jpg',
            stock: 70,
            rating: 4.3,
            reviews: 80,
        },
        {
            id: '42',
            name: 'Smartwatch W1',
            price: 199.99,
            size: '44mm',
            category: 'Electronics',
            brand: 'WatchWise',
            description: 'Smartwatch with fitness tracking and notifications.',
            image: 'smartwatch_w1.jpg',
            stock: 55,
            rating: 4.5,
            reviews: 115,
        },
        {
            id: '43',
            name: 'Bluetooth Speaker S4',
            price: 79.99,
            size: 'Portable',
            category: 'Electronics',
            brand: 'SoundBlast',
            description: 'Portable Bluetooth speaker with powerful sound.',
            image: 'speaker_s4.jpg',
            stock: 100,
            rating: 4.7,
            reviews: 175,
        },
        {
            id: '44',
            name: 'E-reader E1',
            price: 149.5,
            size: '6 inches',
            category: 'Electronics',
            brand: 'ReadMore',
            description: 'E-reader with built-in light and long battery life.',
            image: 'ereader_e1.jpg',
            stock: 60,
            rating: 4.4,
            reviews: 90,
        },
        {
            id: '45',
            name: "Women's Dress D3",
            price: 59.99,
            size: 'Small',
            category: 'Clothing',
            brand: 'FashionForward',
            description: 'Stylish and comfortable dress for any occasion.',
            image: 'dress_d3.jpg',
            stock: 80,
            rating: 4.6,
            reviews: 130,
        },
        {
            id: '46',
            name: "Men's Shirt S5",
            price: 39.5,
            size: 'Medium',
            category: 'Clothing',
            brand: 'CasualWear',
            description: "Classic and versatile men's shirt.",
            image: 'shirt_s5.jpg',
            stock: 100,
            rating: 4.3,
            reviews: 75,
        },
        {
            id: '47',
            name: "Women's Jeans J1",
            price: 79.99,
            size: 'Size 6',
            category: 'Clothing',
            brand: 'DenimDiva',
            description: "Comfortable and stylish women's jeans.",
            image: 'jeans_j1.jpg',
            stock: 65,
            rating: 4.5,
            reviews: 105,
        },
        {
            id: '48',
            name: "Men's Shoes S6",
            price: 99.5,
            size: "Men's 9",
            category: 'Clothing',
            brand: 'ShoeStyle',
            description: 'Dress shoes for men, perfect for formal occasions.',
            image: 'shoes_s6.jpg',
            stock: 50,
            rating: 4.7,
            reviews: 140,
        },
        {
            id: '49',
            name: "Women's Boots B7",
            price: 129.99,
            size: "Women's 8",
            category: 'Clothing',
            brand: 'BootBabe',
            description: "Fashionable and comfortable women's boots.",
            image: 'boots_b7.jpg',
            stock: 40,
            rating: 4.4,
            reviews: 85,
        },
        {
            id: '50',
            name: 'Unisex Jacket J2',
            price: 89.5,
            size: 'Large',
            category: 'Clothing',
            brand: 'Outerwear',
            description: 'Lightweight and versatile unisex jacket.',
            image: 'jacket_j2.jpg',
            stock: 90,
            rating: 4.6,
            reviews: 120,
        },
    ];
};

export default productListMock;
